# Generated by Django 5.1.6 on 2025-04-06 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='source_polls',
            field=models.ManyToManyField(related_name='datasets', to='polls.poll', verbose_name='Source Polls'),
        ),
        migrations.AddField(
            model_name='analyticsjob',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='analytics.dataset', verbose_name='Dataset'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='datasets',
            field=models.ManyToManyField(related_name='reports', to='analytics.dataset', verbose_name='Datasets'),
        ),
        migrations.AddField(
            model_name='visualization',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='visualization',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='analytics.dataset', verbose_name='Dataset'),
        ),
    ]
