# Generated by Django 5.1.6 on 2025-03-11 10:02

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('polls', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='related_poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='polls.poll', verbose_name='Related Poll'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending_events', to=settings.AUTH_USER_MODEL, verbose_name='Attendees'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='polls.poll', verbose_name='Related Poll'),
        ),
        migrations.AddField(
            model_name='impact',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='polls.poll', verbose_name='Poll'),
        ),
        migrations.AddField(
            model_name='impact',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_impacts', to=settings.AUTH_USER_MODEL, verbose_name='Reported By'),
        ),
        migrations.AddField(
            model_name='impact',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_impacts', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='interested_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Interested Users'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='related_poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_opportunities', to='polls.poll', verbose_name='Related Poll'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
