# Generated by Django 5.1.6 on 2025-03-14 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
