# Generated by Django 5.1.6 on 2025-03-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_pollcomment_options_pollcomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='requires_choices',
            field=models.BooleanField(default=False, verbose_name='Requires Choices'),
        ),
    ]
