# Generated by Django 5.1.6 on 2025-04-06 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_comment', models.BooleanField(default=True, verbose_name='Email for comments')),
                ('email_event_reminder', models.BooleanField(default=True, verbose_name='Email for event reminders')),
                ('email_event_attendance', models.BooleanField(default=True, verbose_name='Email for event attendance')),
                ('email_opportunity_interest', models.BooleanField(default=True, verbose_name='Email for opportunity interest')),
                ('email_impact_verified', models.BooleanField(default=True, verbose_name='Email for impact verification')),
                ('email_mention', models.BooleanField(default=True, verbose_name='Email for mentions')),
                ('email_discussion_reply', models.BooleanField(default=True, verbose_name='Email for discussion replies')),
                ('email_system', models.BooleanField(default=True, verbose_name='Email for system notifications')),
                ('app_comment', models.BooleanField(default=True, verbose_name='In-app for comments')),
                ('app_event_reminder', models.BooleanField(default=True, verbose_name='In-app for event reminders')),
                ('app_event_attendance', models.BooleanField(default=True, verbose_name='In-app for event attendance')),
                ('app_opportunity_interest', models.BooleanField(default=True, verbose_name='In-app for opportunity interest')),
                ('app_impact_verified', models.BooleanField(default=True, verbose_name='In-app for impact verification')),
                ('app_mention', models.BooleanField(default=True, verbose_name='In-app for mentions')),
                ('app_discussion_reply', models.BooleanField(default=True, verbose_name='In-app for discussion replies')),
                ('app_system', models.BooleanField(default=True, verbose_name='In-app for system notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'New Comment'), ('event_reminder', 'Event Reminder'), ('event_attendance', 'New Event Attendee'), ('opportunity_interest', 'New Opportunity Interest'), ('impact_verified', 'Impact Report Verified'), ('mention', 'User Mention'), ('discussion_reply', 'Reply to Your Discussion'), ('system', 'System Notification')], max_length=50, verbose_name='Notification Type')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read Status')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx')],
            },
        ),
    ]
